[project]
name = "index-benchmark"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "requests",
    "markdownify",
    "tqdm",
    "torch",
    "accelerate",
    "bitsandbytes",
    "transformers",
    "bm25s",
    "mistralai",
    "openai",
    "google-genai",
    "cohere",
    "voyageai",
    "pandas",
    "seaborn",
    "matplotlib",
    "sentence-transformers",
    "luxical",
]
